ticket/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages
  resources :users

  root "messages#index"
end

ticket/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ticket/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from, class_name: "User", foreign_key: :from_id
  belongs_to :to, class_name: "User", foreign_key: :to_id

  after_create :send_simple_message

  private
    def send_simple_message
      # Call api mailgun to send email.
      # The call is executed when after a message is created.
      RestClient.post "https://api:key-82a0a52cbee4743b1064e8ad713b81f5"\
        "@api.mailgun.net/v3/sandbox11b4809092fe470488c5cd1324599ca2.mailgun.org/messages",
        from: "#{self.from.email} <postmaster@sandbox11b4809092fe470488c5cd1324599ca2.mailgun.org>",
        to: self.to.email,
        subject: self.subject,
        text: self.body
    end
end

ticket/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :inbox, class_name: "Message", foreign_key: :to_id
  has_many :sends, class_name: "Message", foreign_key: :from_id
end

ticket/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ticket/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # devise method to verified user connected.
  before_action :authenticate_user!

  def create
    @message = Message.new(message_params)
    @message.from = current_user
    if @message.save
      return redirect_to messages_path, notice: 'Message created.'
    else
      render :index
    end
  end

  def index
    @message = Message.new
    @users = User.where.not(id: current_user.id).order(:email)
  end

  private
    def message_params
      params.require(:message)
             .permit(:to_id, :subject, :body)
    end
end

ticket/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # devise method to verified user connected.
  before_action :authenticate_user!
  # call method to verify when user is admin
  before_action :verify_admin
  # call method to find user when params id is present.
  before_action :find_user

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User updated.'
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def destroy
    if @user.delete
      redirect_to users_path, notice: 'User deleted.'
    end
  end

  private
    def verify_admin
      return if current_user.admin
      redirect_to messages_path, notice: "You don't have access"
    end

    def find_user
      @user = User.find params[:id] if params[:id]
    end

    def user_params
      params.require(:user)
            .permit(:email, :password, :admin)
    end
end

ticket/app/helpers/application_helper.rb
module ApplicationHelper
end

ticket/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shareds/navbar' %>

    <div class="container-fluid">
      <%= render partial: "shareds/flash_messages", flash: flash %>

      <%= yield %>
    </div>
  </body>
</html>

ticket/app/views/messages/index.html.erb
<%= form_for @message do |f| %>
  <%= render partial: 'shareds/error_messages', locals: { model: @message } %>

  <div class="form-group">
    <%= f.label :to %>
    <%= f.select :to_id, options_from_collection_for_select(@users, "id", "email") %>
  </div>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 5, required: true %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

ticket/app/views/shareds/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger" id="error_explanation">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong><%= t('errors.template.header', model: model.class.model_name.human, count: model.errors.count) %></strong>

    <ul class="list-unstyled">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

ticket/app/views/shareds/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissable fade in ">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

ticket/app/views/shareds/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Test</a></div>
      <nav class="collapse navbar-collapse">
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li class="<%= "active" if params[:controller] == "messages" %>"><%= link_to 'Messages', messages_path %></li>
            <li class="<%= "active" if params[:controller] == "users" %>"><%= link_to 'Users', users_path %></li>
          </ul>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      </nav>
  </div>
</nav>

ticket/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'shareds/error_messages', locals: { model: @user } %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :admin %>
    <%= f.select :admin, [['Yes', true], ['No', false]], {}, { class: 'form-control' } %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

ticket/app/views/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td><%= user.admin ? "Yes" : "No" %></td>
  <td>(<%= user.inbox.count %>) message(s)</td>
  <td>(<%= user.sends.count %>) message(s)</td>
  <td><%= l user.created_at, format: :short %></td>
  <td><%= link_to "Edit", edit_user_path(user) %> | <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } if user != current_user %></td>
</tr>

ticket/app/views/users/edit.html.erb
<%= render "form" %>

ticket/app/views/users/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th>Inbox</th>
      <th>Sends</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>